version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  linux-gcc:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      CC: gcc-9
      CXX: g++-9
    steps:
      - checkout
      - run:
          name: Build software
          command: |
            sudo apt-get update
            sudo apt-get install -y ninja-build git unzip cmake g++-9 libstdc++-9-dev
      - run: /bin/bash ./.ci/build-project.sh
      - store_artifacts:
          path: output/mycmd

  windows-msvc:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Download CMake
          command: |
            $ProgressPreference = "SilentlyContinue"
            Invoke-WebRequest -URI https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-win64-x64.zip -OutFile $Env:HOMEPATH\cmake-3.16.4-win64-x64.zip
            Expand-Archive $Env:HOMEPATH\cmake-3.16.4-win64-x64.zip -DestinationPath "$Env:ProgramFiles"
            Rename-Item "$Env:ProgramFiles\cmake-3.16.4-win64-x64" -NewName CMake
      - run: .ci\build-project.ps1
      - store_artifacts:
          path: build/mycmd.exe

workflows:
  version: 2
  run-all:
    jobs:
      - linux-gcc
